[package]
name = "guild-registry"
version.workspace = true
edition.workspace = true

[dependencies]
base64.workspace = true
ed25519-dalek.workspace = true
guild-manifest = { path = "../guild-manifest" }
guild-types = { path = "../guild-types" }
rand_core.workspace = true
serde.workspace = true
serde_json.workspace = true
schemars.workspace = true
sha2.workspace = true
walkdir.workspace = true
